config/routes.rb
Fcards::Application.routes.draw do

  resources :decks do
    resources :cards
    get 'study', on: :member
    get 'again_current_card_and_fetch_next', as: "again_this_card", on: :member
    get 'study_tommorow_current_card_and_fetch_next', as: "tommorow_this_card", on: :member
    get 'study_three_days_later_current_card_and_fetch_next', as: "three_days_this_card", on: :member
    get 'study_a_week_later_current_card_and_fetch_next', as: "a_week_this_card", on: :member
    get 'study_a_month_later_current_card_and_fetch_next', as: "a_month_this_card", on: :member
    get 'never_study_current_card_and_fetch_next', as: "never_this_card", on: :member
  end

  devise_for :users

  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
end
#== Route Map
# Generated on 09 Sep 2012 16:26
#
#                           POST   /decks/:deck_id/cards(.:format)                                         cards#create
#             new_deck_card GET    /decks/:deck_id/cards/new(.:format)                                     cards#new
#            edit_deck_card GET    /decks/:deck_id/cards/:id/edit(.:format)                                cards#edit
#                 deck_card GET    /decks/:deck_id/cards/:id(.:format)                                     cards#show
#                           PUT    /decks/:deck_id/cards/:id(.:format)                                     cards#update
#                           DELETE /decks/:deck_id/cards/:id(.:format)                                     cards#destroy
#                study_deck GET    /decks/:id/study(.:format)                                              decks#study
#      again_this_card_deck GET    /decks/:id/again_current_card_and_fetch_next(.:format)                  decks#again_current_card_and_fetch_next
#   tommorow_this_card_deck GET    /decks/:id/study_tommorow_current_card_and_fetch_next(.:format)         decks#study_tommorow_current_card_and_fetch_next
# three_days_this_card_deck GET    /decks/:id/study_three_days_later_current_card_and_fetch_next(.:format) decks#study_three_days_later_current_card_and_fetch_next
#     a_week_this_card_deck GET    /decks/:id/study_a_week_later_current_card_and_fetch_next(.:format)     decks#study_a_week_later_current_card_and_fetch_next
#    a_month_this_card_deck GET    /decks/:id/study_a_month_later_current_card_and_fetch_next(.:format)    decks#study_a_month_later_current_card_and_fetch_next
#      never_this_card_deck GET    /decks/:id/never_study_current_card_and_fetch_next(.:format)            decks#never_study_current_card_and_fetch_next
#                     decks GET    /decks(.:format)                                                        decks#index
#                           POST   /decks(.:format)                                                        decks#create
#                  new_deck GET    /decks/new(.:format)                                                    decks#new
#                 edit_deck GET    /decks/:id/edit(.:format)                                               decks#edit
#                      deck GET    /decks/:id(.:format)                                                    decks#show
#                           PUT    /decks/:id(.:format)                                                    decks#update
#                           DELETE /decks/:id(.:format)                                                    decks#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                               devise/sessions#destroy
#             user_password POST   /users/password(.:format)                                               devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)                                           devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                          devise/passwords#edit
#                           PUT    /users/password(.:format)                                               devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)                                                 devise/registrations#cancel
#         user_registration POST   /users(.:format)                                                        devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)                                                devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                   devise/registrations#edit
#                           PUT    /users(.:format)                                                        devise/registrations#update
#                           DELETE /users(.:format)                                                        devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)                                           devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format)                                       devise/confirmations#new
#                           GET    /users/confirmation(.:format)                                           devise/confirmations#show
#                   contact        /contact(.:format)                                                      static_pages#contact
#                     about        /about(.:format)                                                        static_pages#about
#                      root        /                                                                       static_pages#home

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id                  :integer          primary key
#  front               :text
#  back                :text
#  next_study_datetime :timestamp
#  deck_id             :integer
#  created_at          :timestamp        not null
#  updated_at          :timestamp        not null
#  status              :integer          default(0)
#  study_count         :integer          default(0)
#

class Card < ActiveRecord::Base
  attr_accessible :back, :front, :next_study_datetime
  belongs_to :deck
  validates :deck_id, presence: true
  validates :front, presence: true, length: { maximum: 1500 }
  validates :back, presence: true, length: { maximum: 1500 }

  self.per_page = 100

  STATUS_FIRST_TIME = 0
  STATUS_AGAIN = 1
  STATUS_HARD = 2
  STATUS_MEDIUM = 3
  STATUS_EASY = 4
  STATUS_ALMOST_DONE = 5
  STATUS_DONE = 9

  scope :need_to_study, where("next_study_datetime < ?", Time.now ).order("next_study_datetime DESC")
  scope :done, where("status = ?", STATUS_DONE )
  scope :search, lambda { |keyword|
    where 'front like :q or back like :q', q: "%#{keyword}%"
  }

  default_scope order: 'id ASC'

  def study_again!
    self.next_study_datetime = DateTime.now + 20.minutes
    self.status = STATUS_AGAIN
    self.study_count += 1
    save!
  end

  def study_tommorow!
    self.next_study_datetime = DateTime.now + 1.day
    self.status = STATUS_HARD
    self.study_count += 1
    save!
  end

  def study_three_days_later!
    self.next_study_datetime = DateTime.now + 3.days
    self.status = STATUS_MEDIUM
    self.study_count += 1
    save!
  end

  def study_a_week_later!
    self.next_study_datetime = DateTime.now + 1.week
    self.status = STATUS_EASY
    self.study_count += 1
    save!
  end

  def study_a_month_later!
    self.next_study_datetime = DateTime.now + 1.month
    self.status = STATUS_ALMOST_DONE
    self.study_count += 1
    save!
  end

  def never_study!
    self.next_study_datetime = DateTime.now + 999.years
    self.status = STATUS_DONE
    self.study_count += 1
    save!
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |card|
        csv << card.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :authenticate_user!, :find_deck

  # GET /cards
  # GET /cards.json
  def index

    if params[:keyword].present?
      @keyword = params[:keyword]
      @cards = @deck.cards.search(@keyword).paginate(page: params[:page])
    else
      @cards = @deck.cards.paginate(page: params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
      format.csv { send_data @cards.to_csv }
    end
  end

  # get /cards/1
  # get /cards/1.json
  def show
    @card = @deck.cards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # get /cards/new
  # get /cards/new.json
  def new
    @card = @deck.cards.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # get /cards/1/edit
  def edit
    @card = @deck.cards.find(params[:id])
  end

  # post /cards
  # post /cards.json
  def create
    @card = @deck.cards.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to deck_cards_path(@deck), notice: 'card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # put /cards/1
  # put /cards/1.json
  def update
    @card = @deck.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to deck_cards_path(@deck), notice: 'card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # delete /cards/1
  # delete /cards/1.json
  def destroy
    @card = @deck.cards.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to deck_cards_url(@deck) }
      format.json { head :no_content }
    end
  end

  private

  def find_deck
    @deck = current_user.decks.find(params[:deck_id])
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<tr>
  <td><%= card.id %></td>
  <td><%= truncate(card.front, length:80) %></td>
  <td><%= truncate(card.back, length:80) %></td>
  <td><%= display_card_study_count card.study_count %></td>
  <td><%= display_card_status card.status %></td>
  <td><%= link_to 'Show', deck_card_path(@deck, card), class: "btn btn-mini" %></td>
  <td><%= link_to 'Edit', edit_deck_card_path(@deck, card), class: "btn btn-mini" %></td>
  <td><%= link_to 'Destroy', deck_card_path(@deck, card), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-mini btn-danger" %></td>
</tr>

app/views/cards/_form.html.erb
<%= form_for [@deck, @card] do |f| %>
  <% if @card.errors.any? %>
    <div class="alert alert-block alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</strong>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :front %>
  <%= f.text_area :front, placeholder: "Type front...", rows: 3, class: "input-xxlarge" %>
  <%= f.label :back %>
  <%= f.text_area :back, placeholder: "Type back...", rows: 5, class: "input-xxlarge" %>
  <br />
  <%= f.button "Submit", class: "btn btn-primary" %>
<% end %>

app/views/cards/edit.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Editing Card</h1>
    </div>
    <%= render 'form' %>

    <%= link_to 'Show', deck_card_path(@deck, @card), class: "btn" %>
    <%= link_to 'Back', deck_cards_path(@deck), class: "btn"  %>
  </div>
</div>

app/views/cards/index.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Listing cards</h1>
    </div>
    <%= form_tag deck_cards_path(@deck), method: :get, class: "form-search" do %>
      <%= search_field_tag :keyword , nil, placeholder: "Keyword", class: "input-medium search-query"%>
      <%= submit_tag "Search", class: "btn" %>
    <% end %>
    <p>
    <% if @keyword.present? %>
      <strong>Keyword: </strong><span class="label"><%= @keyword %></span>
      <strong>Results: </strong><span class="badge"><%= @cards.count %></span>
    <% end %>
    <%= link_to 'New Card', new_deck_card_path(@deck) %>
    </p>
    <%= will_paginate @cards %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Front</th>
          <th>Back</th>
          <th>Study Count</th>
          <th>Status</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @cards %>
      </tbody>
    </table>

    <br />

    <%= will_paginate @cards %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>New Card</h1>
    </div>
    <%= render 'form' %>

    <%= link_to 'Back', deck_cards_path(@deck), class: "btn"  %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="row">
  <div class="span12">
    <p>Front:</p>
    <div class="well">
      <p><strong><%= @card.front %></strong></p>
    </div>
    <p>Back:</p>
    <div class="well">
      <p><strong><%= @card.back %></strong></p>
    </div>
    <p>
    <p>
    <%= link_to 'Edit', edit_deck_card_path(@deck, @card), class: "btn" %>
    <%= link_to 'Back', deck_cards_path(@deck), class: "btn" %>
  </div>
</div>