config/routes.rb
Fcards::Application.routes.draw do

  resources :decks do
    resources :cards
    get 'study', on: :member
    get 'again_current_card_and_fetch_next', as: "again_this_card", on: :member
    get 'study_tommorow_current_card_and_fetch_next', as: "tommorow_this_card", on: :member
    get 'study_three_days_later_current_card_and_fetch_next', as: "three_days_this_card", on: :member
    get 'study_a_week_later_current_card_and_fetch_next', as: "a_week_this_card", on: :member
    get 'study_a_month_later_current_card_and_fetch_next', as: "a_month_this_card", on: :member
    get 'never_study_current_card_and_fetch_next', as: "never_this_card", on: :member
  end

  devise_for :users

  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
end
#== Route Map
# Generated on 09 Sep 2012 16:26
#
#                           POST   /decks/:deck_id/cards(.:format)                                         cards#create
#             new_deck_card GET    /decks/:deck_id/cards/new(.:format)                                     cards#new
#            edit_deck_card GET    /decks/:deck_id/cards/:id/edit(.:format)                                cards#edit
#                 deck_card GET    /decks/:deck_id/cards/:id(.:format)                                     cards#show
#                           PUT    /decks/:deck_id/cards/:id(.:format)                                     cards#update
#                           DELETE /decks/:deck_id/cards/:id(.:format)                                     cards#destroy
#                study_deck GET    /decks/:id/study(.:format)                                              decks#study
#      again_this_card_deck GET    /decks/:id/again_current_card_and_fetch_next(.:format)                  decks#again_current_card_and_fetch_next
#   tommorow_this_card_deck GET    /decks/:id/study_tommorow_current_card_and_fetch_next(.:format)         decks#study_tommorow_current_card_and_fetch_next
# three_days_this_card_deck GET    /decks/:id/study_three_days_later_current_card_and_fetch_next(.:format) decks#study_three_days_later_current_card_and_fetch_next
#     a_week_this_card_deck GET    /decks/:id/study_a_week_later_current_card_and_fetch_next(.:format)     decks#study_a_week_later_current_card_and_fetch_next
#    a_month_this_card_deck GET    /decks/:id/study_a_month_later_current_card_and_fetch_next(.:format)    decks#study_a_month_later_current_card_and_fetch_next
#      never_this_card_deck GET    /decks/:id/never_study_current_card_and_fetch_next(.:format)            decks#never_study_current_card_and_fetch_next
#                     decks GET    /decks(.:format)                                                        decks#index
#                           POST   /decks(.:format)                                                        decks#create
#                  new_deck GET    /decks/new(.:format)                                                    decks#new
#                 edit_deck GET    /decks/:id/edit(.:format)                                               decks#edit
#                      deck GET    /decks/:id(.:format)                                                    decks#show
#                           PUT    /decks/:id(.:format)                                                    decks#update
#                           DELETE /decks/:id(.:format)                                                    decks#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                               devise/sessions#destroy
#             user_password POST   /users/password(.:format)                                               devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)                                           devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                          devise/passwords#edit
#                           PUT    /users/password(.:format)                                               devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)                                                 devise/registrations#cancel
#         user_registration POST   /users(.:format)                                                        devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)                                                devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                   devise/registrations#edit
#                           PUT    /users(.:format)                                                        devise/registrations#update
#                           DELETE /users(.:format)                                                        devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)                                           devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format)                                       devise/confirmations#new
#                           GET    /users/confirmation(.:format)                                           devise/confirmations#show
#                   contact        /contact(.:format)                                                      static_pages#contact
#                     about        /about(.:format)                                                        static_pages#about
#                      root        /                                                                       static_pages#home

app/models/deck.rb
# == Schema Information
#
# Table name: decks
#
#  id          :integer          primary key
#  title       :string(255)
#  description :text
#  user_id     :integer
#  created_at  :timestamp        not null
#  updated_at  :timestamp        not null
#

class Deck < ActiveRecord::Base
  attr_accessible :description, :title
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 250 }
  has_many :cards, dependent: :destroy

  def progress
    if self.cards.count > 0
      100 * self.cards.done.count / self.cards.count
    else
      return 0
    end
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate_user!

  # GET /decks
  # GET /decks.json
  def index
    @decks = current_user.decks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @decks }
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    @deck = current_user.decks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/new
  # GET /decks/new.json
  def new
    @deck = Deck.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deck }
    end
  end

  # GET /decks/1/edit
  def edit
    @deck = current_user.decks.find(params[:id])
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = current_user.decks.build(params[:deck])

    respond_to do |format|
      if @deck.save
        format.html { redirect_to decks_path , notice: 'Deck was successfully created.' }
        format.json { render json: @deck, status: :created, location: @deck }
      else
        format.html { render action: "new" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /decks/1
  # PUT /decks/1.json
  def update
    @deck = current_user.decks.find(params[:id])

    respond_to do |format|
      if @deck.update_attributes(params[:deck])
        format.html { redirect_to decks_path , notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck = current_user.decks.find(params[:id])
    @deck.destroy

    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end

  def study
    @deck = current_user.decks.find(params[:id])
    @cards_count = @deck.cards.need_to_study.count
    @card = @deck.cards.need_to_study.first
  end

  def again_current_card_and_fetch_next
    @deck = current_user.decks.find(params[:id])
    @card = @deck.cards.need_to_study.first
    @card.study_again!
    redirect_to study_deck_url(@deck)
  end

  def study_tommorow_current_card_and_fetch_next
    @deck = current_user.decks.find(params[:id])
    @card = @deck.cards.need_to_study.first
    @card.study_tommorow!
    redirect_to study_deck_url(@deck)
  end

  def study_three_days_later_current_card_and_fetch_next
    @deck = current_user.decks.find(params[:id])
    @card = @deck.cards.need_to_study.first
    @card.study_three_days_later!
    redirect_to study_deck_url(@deck)
  end

  def study_a_week_later_current_card_and_fetch_next
    @deck = current_user.decks.find(params[:id])
    @card = @deck.cards.need_to_study.first
    @card.study_a_week_later!
    redirect_to study_deck_url(@deck)
  end

  def study_a_month_later_current_card_and_fetch_next
    @deck = current_user.decks.find(params[:id])
    @card = @deck.cards.need_to_study.first
    @card.study_a_month_later!
    redirect_to study_deck_url(@deck)
  end

  def never_study_current_card_and_fetch_next
    @deck = current_user.decks.find(params[:id])
    @card = @deck.cards.need_to_study.first
    @card.never_study!
    redirect_to study_deck_url(@deck)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_deck.html.erb
<tr>
  <td><%= link_to 'Study Deck', study_deck_path(deck), class: "btn btn-mini btn-primary" %></td>
  <td><%= link_to 'Show Cards', deck_cards_path(deck), class: "btn btn-mini btn-info" %></td>
  <td><%= link_to 'Export Cards', deck_cards_path(deck, format: "csv"), class: "btn btn-mini btn-info" %></td>
  <td><%= link_to truncate(deck.title, length: 80), deck %></td>
  <td><%= truncate(deck.description, length: 80) %></td>
  <td><%= content_tag(:span, deck.cards.count, class: "label") %></td>
  <td><%= content_tag(:span, deck.progress.to_s + "%", class: "label label-success") %></td>
  <td><%= link_to 'Edit', edit_deck_path(deck), class: "btn btn-mini" %></td>
</tr>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div class="alert alert-block alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Type title...", class: "input-xxlarge" %>
  <%= f.label :description %>
  <%= f.text_area :description, placeholder: "Type description...", rows: 3, class: "input-xxlarge" %>
  <br />
  <%= f.button "Submit", class: "btn btn-primary" %>
<% end %>

app/views/decks/edit.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Editing Deck</h1>
    </div>
    <%= render 'form' %>

    <%= link_to 'Destroy', @deck, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

    <%= link_to 'Show', @deck, class: "btn" %>
    <%= link_to 'Back', decks_path, class: "btn"  %>
  </div>
</div>

app/views/decks/index.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>Listing decks</h1>
    </div>
    <%= link_to 'New Deck', new_deck_path, title: "Create a new deck", rel: "tooltip", "data-placement" => "right" %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th>Title</th>
          <th>Description</th>
          <th>Cards Number</th>
          <th>Progress</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @decks %>
      </tbody>
    </table>
  </div>
</div>

app/views/decks/new.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h1>New Deck</h1>
    </div>
    <%= render 'form' %>

    <%= link_to 'Back', decks_path, class: "btn"  %>
  </div>
</div>

app/views/decks/show.html.erb
<div class="row">
  <div class="span12">
    <p>
    <b>Title:</b>
    <%= @deck.title %>
    </p>

    <p>
    <b>Description:</b>
    <%= @deck.description %>
    </p>

    <%= link_to 'Edit', edit_deck_path(@deck), class: "btn" %>
    <%= link_to 'Back', decks_path, class: "btn" %>
  </div>
</div>

app/views/decks/study.html.erb
<% provide(:title, "Study " + @deck.title) %>
<div class="row">
  <div class="span12">
    <%if @card.present? %>
      <p>
      <%= display_card_status @card.status %>
      <strong>Count: </strong><%= display_card_study_count @card.study_count %>
      <strong>Cards: </strong><span class="badge"><%= @cards_count %></span></p>
      <hr>
      <div class="well">
        <h1><%= @card.front %></h1><br>
        <button type="button" class="btn" data-toggle="collapse" data-target="#back">
          Show Answer
        </button>
      </div>
      <div id="back" class="collapse">
        <div class="well">
          <p><strong><%= @card.back %></strong></p>
        </div>
      </div>
      <p>
      <%= link_to 'Again', again_this_card_deck_path(@deck), class: "btn btn-mini btn-danger" %>
      <%= link_to 'Hard', tommorow_this_card_deck_path(@deck), class: "btn btn-mini btn-warning" %>
      <%= link_to 'Med', three_days_this_card_deck_path(@deck), class: "btn btn-mini btn-success" %>
      <%= link_to 'Easy', a_week_this_card_deck_path(@deck), class: "btn btn-mini btn-info" %>
      <%= link_to 'Almost', a_month_this_card_deck_path(@deck), class: "btn btn-mini btn-primary" %>
      <%= link_to 'Done', never_this_card_deck_path(@deck), class: "btn btn-mini btn-inverse" %>
      </p>
    <% else %>
      <h1>No card to study! Wow!</h1>
    <% end %>
  </div>
</div>