config/routes.rb
Fcards::Application.routes.draw do

  resources :decks do
    resources :cards
    get 'study', on: :member
    get 'again_current_card_and_fetch_next', as: "again_this_card", on: :member
    get 'study_tommorow_current_card_and_fetch_next', as: "tommorow_this_card", on: :member
    get 'study_three_days_later_current_card_and_fetch_next', as: "three_days_this_card", on: :member
    get 'study_a_week_later_current_card_and_fetch_next', as: "a_week_this_card", on: :member
    get 'study_a_month_later_current_card_and_fetch_next', as: "a_month_this_card", on: :member
    get 'never_study_current_card_and_fetch_next', as: "never_this_card", on: :member
  end

  devise_for :users

  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  root to: 'static_pages#home'
end
#== Route Map
# Generated on 09 Sep 2012 16:26
#
#                           POST   /decks/:deck_id/cards(.:format)                                         cards#create
#             new_deck_card GET    /decks/:deck_id/cards/new(.:format)                                     cards#new
#            edit_deck_card GET    /decks/:deck_id/cards/:id/edit(.:format)                                cards#edit
#                 deck_card GET    /decks/:deck_id/cards/:id(.:format)                                     cards#show
#                           PUT    /decks/:deck_id/cards/:id(.:format)                                     cards#update
#                           DELETE /decks/:deck_id/cards/:id(.:format)                                     cards#destroy
#                study_deck GET    /decks/:id/study(.:format)                                              decks#study
#      again_this_card_deck GET    /decks/:id/again_current_card_and_fetch_next(.:format)                  decks#again_current_card_and_fetch_next
#   tommorow_this_card_deck GET    /decks/:id/study_tommorow_current_card_and_fetch_next(.:format)         decks#study_tommorow_current_card_and_fetch_next
# three_days_this_card_deck GET    /decks/:id/study_three_days_later_current_card_and_fetch_next(.:format) decks#study_three_days_later_current_card_and_fetch_next
#     a_week_this_card_deck GET    /decks/:id/study_a_week_later_current_card_and_fetch_next(.:format)     decks#study_a_week_later_current_card_and_fetch_next
#    a_month_this_card_deck GET    /decks/:id/study_a_month_later_current_card_and_fetch_next(.:format)    decks#study_a_month_later_current_card_and_fetch_next
#      never_this_card_deck GET    /decks/:id/never_study_current_card_and_fetch_next(.:format)            decks#never_study_current_card_and_fetch_next
#                     decks GET    /decks(.:format)                                                        decks#index
#                           POST   /decks(.:format)                                                        decks#create
#                  new_deck GET    /decks/new(.:format)                                                    decks#new
#                 edit_deck GET    /decks/:id/edit(.:format)                                               decks#edit
#                      deck GET    /decks/:id(.:format)                                                    decks#show
#                           PUT    /decks/:id(.:format)                                                    decks#update
#                           DELETE /decks/:id(.:format)                                                    decks#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                               devise/sessions#destroy
#             user_password POST   /users/password(.:format)                                               devise/passwords#create
#         new_user_password GET    /users/password/new(.:format)                                           devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                          devise/passwords#edit
#                           PUT    /users/password(.:format)                                               devise/passwords#update
#  cancel_user_registration GET    /users/cancel(.:format)                                                 devise/registrations#cancel
#         user_registration POST   /users(.:format)                                                        devise/registrations#create
#     new_user_registration GET    /users/sign_up(.:format)                                                devise/registrations#new
#    edit_user_registration GET    /users/edit(.:format)                                                   devise/registrations#edit
#                           PUT    /users(.:format)                                                        devise/registrations#update
#                           DELETE /users(.:format)                                                        devise/registrations#destroy
#         user_confirmation POST   /users/confirmation(.:format)                                           devise/confirmations#create
#     new_user_confirmation GET    /users/confirmation/new(.:format)                                       devise/confirmations#new
#                           GET    /users/confirmation(.:format)                                           devise/confirmations#show
#                   contact        /contact(.:format)                                                      static_pages#contact
#                     about        /about(.:format)                                                        static_pages#about
#                      root        /                                                                       static_pages#home

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, '<a class="close" data-dismiss="alert" href="#">×</a>'.html_safe + value, class: "alert alert-#{key}" %>
<% end %>

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
<p>&copy; F-CARDS 2013</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
<div class="navbar-inner">
  <div class="container">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <%= link_to "F-CARDS", root_path, class: "brand" %>
    <ul class="nav pull-right">
      <% if user_signed_in? %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-large"></i><span class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%=link_to "Decks", decks_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: "delete" %></li>
        </ul>
        </li>
      <% else %>
        <li<%= " class='active'".html_safe if current_page?(new_user_registration_path) %>><%= link_to "Sign up", new_user_registration_path %></li>
        <li<%= " class='active'".html_safe if current_page?(new_user_session_path) %>><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
    <div class="nav-collapse collapse">
      <ul class="nav">
        <li<%= " class='active'".html_safe if current_page?(root_path) %>><%= link_to "Home", root_path %></li>
        <li<%= " class='active'".html_safe if current_page?(about_path) %>><%= link_to "About", about_path %></li>
        <li<%= " class='active'".html_safe if current_page?(contact_path) %>><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="This is the site which helps you memorize things">
    <meta name="author" content="masay0shi">
    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <%= csrf_meta_tags %>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash_message' if flash.present? %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>